/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPopupMenu;

/**
 *
 * @author E6540
 */
public class ImgInChat extends javax.swing.JPanel {

    /**
     * Creates new form ImgInChat
     */
    public ImgInChat() {
        initComponents();
    }
    
     private boolean isOver = false;

    public ImageIcon getImage() {
        return image;
    }

    public void setImage(ImageIcon image) {
        this.image = image;
    }

    private ImageIcon image;

    public void setPhoto(ImageIcon image) {
        this.image = image;
        Image img;
        if (image.getIconHeight() > 200 || image.getIconWidth() > 200) {
            if (image.getIconWidth() > image.getIconHeight()) {
                img = image.getImage().getScaledInstance(200, -1, Image.SCALE_SMOOTH);
            } else {
                img = image.getImage().getScaledInstance(-1, 200, Image.SCALE_SMOOTH);
            }
            ImageIcon icon = new ImageIcon(img);
            label_Img.setIcon(icon);
        } else {
            label_Img.setIcon(image);
            this.setPreferredSize(new Dimension(600, image.getIconHeight() + 12));
            this.setMaximumSize(new Dimension(600, image.getIconHeight() + 12));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_Img = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(300, 300));
        setPreferredSize(new java.awt.Dimension(200, 200));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        label_Img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_ImgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_ImgMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                label_ImgMouseReleased(evt);
            }
        });
        add(label_Img);
    }// </editor-fold>//GEN-END:initComponents

    private void label_ImgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_ImgMouseEntered
        this.isOver = true;
    }//GEN-LAST:event_label_ImgMouseEntered

    private void label_ImgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_ImgMouseExited
        this.isOver = false;
    }//GEN-LAST:event_label_ImgMouseExited

    private void label_ImgMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_ImgMouseReleased
        if(isOver)
        {
            JPopupMenu pop = new JPopupMenu();
            pop.setBackground(new Color(0, 0, 0, 0));
            ImageViewer obj = new ImageViewer();
            obj.setImage(image);
            pop.add(obj);
            int w = (int) obj.getPreferredSize().getWidth();
            int h = (int) obj.getPreferredSize().getHeight();
            pop.show(this, w, h);
        }
    }//GEN-LAST:event_label_ImgMouseReleased

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label_Img;
    // End of variables declaration//GEN-END:variables
}
