/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import Models.USER;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author E6540
 */
public class ListFriends extends javax.swing.JPanel implements USER {

    private ImageIcon ava;
    private String userName;
    private Boolean notification;
    private String fullName;
    private String userStatus;

    @Override
    public void set(ImageIcon img, String userName, String name, String status) {
        if (img != null) {
            Image image;
            if (img.getIconWidth() > img.getIconHeight()) {
                image = img.getImage().getScaledInstance(60, -1, Image.SCALE_SMOOTH);
            } else {
                image = img.getImage().getScaledInstance(-1, 60, Image.SCALE_SMOOTH);
            }
            ava = new ImageIcon(image);
            this.label_Ava_listFriend.setIcon(ava);
        }

        this.userName = userName;
        this.fullName = name;
        this.userStatus = status;

        this.label_friendName.setText(name);
        this.label_statusFriend.setText(status);
        if (status.equals("Online")) {
            this.label_statusFriend.setForeground(Color.GREEN);
        } else {
            this.label_statusFriend.setForeground(Color.RED);
        }
        
    }

    public void setBgClicked() {
        this.panel_clicked.setBackground(new Color(37, 222, 141));
    }

    public void RemoveBg() {
        this.panel_clicked.setBackground(new Color(191,226,202));
    }

    public ImageIcon getAva() {
        return ava;
    }

    public void setAva(ImageIcon ava) {
        this.ava = ava;
    }

    public String getFriendUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getUserStatus() {
        return userStatus;
    }

    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus;
    }

    public void updateStatus(String status) {
        this.label_statusFriend.setText(status);
        if (status.equals("Online")) {
            this.label_statusFriend.setForeground(Color.GREEN);
        } else {
            this.label_statusFriend.setForeground(Color.RED);
        }

    }

    public JPanel getPanel_listFriends() {
        return panel_listFriends;
    }

    public void setPanel_listFriends(JPanel panel_listFriends) {
        this.panel_listFriends = panel_listFriends;
    }

    public void setLabel_notification() {
        this.label_notification.setIcon(new ImageIcon(getClass().getResource("/Image/notification.png")));
    }

    public void removeNotification()
    {
        this.label_notification.setIcon(null);
    }
    
    public Boolean getNotification() {
        return notification;
    }

    public void setNotification(Boolean notification) {
        if (notification) {
            this.label_notification.setIcon(new ImageIcon(getClass().getResource("/Image/notification.png")));
        } else {
            this.label_notification.setIcon(null);
        }
    }

    @Override
    public ImageIcon getImgIcon() {
        return this.ava;
    }

    public ListFriends() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_listFriends = new javax.swing.JPanel();
        panel_clicked = new javax.swing.JPanel();
        layerPane_listFriends = new javax.swing.JLayeredPane();
        label_borderAva_listFriend = new javax.swing.JLabel();
        label_Ava_listFriend = new javax.swing.JLabel();
        panel_infoFriends = new javax.swing.JPanel();
        label_friendName = new javax.swing.JLabel();
        label_statusFriend = new javax.swing.JLabel();
        label_notification = new javax.swing.JLabel();
        panel_space = new javax.swing.JPanel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(255, 65));
        setPreferredSize(new java.awt.Dimension(255, 65));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        panel_listFriends.setBackground(new java.awt.Color(191, 226, 202));
        panel_listFriends.setMaximumSize(new java.awt.Dimension(255, 60));
        panel_listFriends.setMinimumSize(new java.awt.Dimension(248, 60));
        panel_listFriends.setPreferredSize(new java.awt.Dimension(255, 60));
        panel_listFriends.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 1, 1));

        panel_clicked.setBackground(new java.awt.Color(191, 226, 202));
        panel_clicked.setMaximumSize(new java.awt.Dimension(10, 65));
        panel_clicked.setPreferredSize(new java.awt.Dimension(10, 60));

        javax.swing.GroupLayout panel_clickedLayout = new javax.swing.GroupLayout(panel_clicked);
        panel_clicked.setLayout(panel_clickedLayout);
        panel_clickedLayout.setHorizontalGroup(
            panel_clickedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panel_clickedLayout.setVerticalGroup(
            panel_clickedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        panel_listFriends.add(panel_clicked);

        layerPane_listFriends.setLayout(new javax.swing.OverlayLayout(layerPane_listFriends));

        label_borderAva_listFriend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/borderAva-listFriends.png"))); // NOI18N
        layerPane_listFriends.add(label_borderAva_listFriend);

        label_Ava_listFriend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ava-listFriends.png"))); // NOI18N
        layerPane_listFriends.add(label_Ava_listFriend);

        panel_listFriends.add(layerPane_listFriends);

        panel_infoFriends.setBackground(new java.awt.Color(191, 226, 202));
        panel_infoFriends.setMaximumSize(new java.awt.Dimension(32767, 60));
        panel_infoFriends.setMinimumSize(new java.awt.Dimension(100, 60));
        panel_infoFriends.setPreferredSize(new java.awt.Dimension(160, 60));
        panel_infoFriends.setLayout(new javax.swing.BoxLayout(panel_infoFriends, javax.swing.BoxLayout.Y_AXIS));

        label_friendName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label_friendName.setText("YOUR FRIENDS NAME");
        label_friendName.setMaximumSize(new java.awt.Dimension(160, 40));
        label_friendName.setPreferredSize(new java.awt.Dimension(160, 14));
        panel_infoFriends.add(label_friendName);

        label_statusFriend.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        label_statusFriend.setForeground(new java.awt.Color(0, 153, 0));
        label_statusFriend.setText("ONLINE");
        label_statusFriend.setMaximumSize(new java.awt.Dimension(160, 15));
        label_statusFriend.setPreferredSize(new java.awt.Dimension(160, 15));
        panel_infoFriends.add(label_statusFriend);

        panel_listFriends.add(panel_infoFriends);

        label_notification.setMaximumSize(new java.awt.Dimension(20, 60));
        label_notification.setPreferredSize(new java.awt.Dimension(20, 60));
        panel_listFriends.add(label_notification);

        add(panel_listFriends);

        panel_space.setBackground(new java.awt.Color(191, 226, 202));
        panel_space.setMaximumSize(new java.awt.Dimension(255, 5));
        panel_space.setPreferredSize(new java.awt.Dimension(255, 5));

        javax.swing.GroupLayout panel_spaceLayout = new javax.swing.GroupLayout(panel_space);
        panel_space.setLayout(panel_spaceLayout);
        panel_spaceLayout.setHorizontalGroup(
            panel_spaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );
        panel_spaceLayout.setVerticalGroup(
            panel_spaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        add(panel_space);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label_Ava_listFriend;
    private javax.swing.JLabel label_borderAva_listFriend;
    private javax.swing.JLabel label_friendName;
    private javax.swing.JLabel label_notification;
    private javax.swing.JLabel label_statusFriend;
    private javax.swing.JLayeredPane layerPane_listFriends;
    private javax.swing.JPanel panel_clicked;
    private javax.swing.JPanel panel_infoFriends;
    private javax.swing.JPanel panel_listFriends;
    private javax.swing.JPanel panel_space;
    // End of variables declaration//GEN-END:variables

}
